### PR TITLE
Leaflet 1.0 canvas

### PR DESCRIPTION
**Pull request by w8r**
* canvas renderer support
* code re-organized
* repeated dragging fixed for DOM renderers

### CODE REVIEW

**Comment by kaynz** [comment]
Hi, is this working for you?
I can't drag polygons on touch devices.

I did some tests: a 'clicked'-event is fired, so it can't be a z-index problem.

**Comment by w8r** [comment]
Let me check. You are sure you are on correct branch?

**Comment by kaynz** [comment]
Yes, I used latest HEAD from leaflet-master and from your branch.

**Comment by w8r** [comment]
Yep, I see, touch events are not really handled in the code, will have to add that. As the matter of fact I don't believe the previous version works on touch as well

**Comment by kaynz** [comment]
Hey, any news on touch events? : )

**Comment by w8r** [comment]
@kaynz, haha you caught me working on that this very moment

**Comment by kaynz** [comment]
@w8r, haha, enjoy and all the best :)

**Comment by w8r** [comment]
@kaynz, I have a working solution for touch devices, but canvas renderers keep on breaking on me. SVG is totally stable, I can release a RC version. Asking you cause you're the only one here showing some interest.

**Comment by kaynz** [comment]
@w8r, thanks, i would like to test it.. maybe i can provide a fix for you :)

**Comment by w8r** [comment]
@kaynz I pushed the code to **leaflet-1.0** branch, you can take a look. I'm still thinking on the publishing strategy to keep both leaflet versions support.

**Comment by w8r** [comment]
@kaynz did you get a chance to look at it?

**Comment by kaynz** [comment]
@w8r, Hey Alex, just started to try some things out, will report later on

**Comment by kaynz** [comment]
Okay, canvas is really buggy. Can't find a fast solution for this, will need some more effort.

But found some bugs in SVG and mobile devices, too, and will concentrate on them for the first.

Sometimes my map gets locked and I can't move it anymore. Sometimes my polygon disappears. It's really hard to provide a fiddle for this because the bugs appear suddenly and can't be reproduced by doing the same again. =(

**Comment by w8r** [comment]
@kaynz thanks, I think those bugs can be caused by overlapping svg's when multiple features attempt to be dragged somehow.

**Comment by kaynz** [comment]
@w8r, thanks for the info. I had a leaflet circle (which was not draggable) as a container for some stuff and inside this container was my draggable polygon. trying to use canvas renderer for the circle and svg for the polygon to test again.

**Comment by kaynz** [comment]
Hey,

with latest leaflet and leaflet.editable things are going pretty good with path.drag!
Actually I'm only working with SVG, had no time for the canvas fixes.

**Pull request merged**
